name: FAVOR_DEPLOY

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Setup
        run: |
          npm i

      - name: Build
        run: |
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist